[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

# Mouse selection copies to clipboard
[selection]
save_to_clipboard = true

# Scrollback buffer
[scrolling]
history = 10000


[window]
option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
