theme = "ayu_dark"

[editor]
line-number = "relative"
auto-pairs = false
cursorline = true
mouse = true
auto-format = true
auto-save = true
rulers = [80]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.lsp]
display-messages = true

[keys.normal]
"]"= {j = "jump_forward"}
"[" = {j = "jump_backward"}
