#!/bin/sh

# navigate to classroom first, so we start in that directory by default
cd ~/src/classroom
session="classroom"
tmux start-server

# start a new session called "classroom", first window named logan
tmux new-session -d -s $session -n logan

# set dir to logan, run npm start
tmux send-keys "cd ~/src/logan;npm start" C-m

# make new window, start classroom server (after waiting for logan to come up)
tmux new-window -t $session:1 -n server
tmux send-keys "sleep 5; nodemon app.js | ./node_modules/.bin/bunyan" C-m

# make new window, split horizontally. Run make dev in first pane (second pane is for tsc)
tmux new-window -t $session:2 -n build
tmux send-keys "make dev" C-m
tmux splitw -h -p 50

# make new window (for nvim)
tmux new-window -t $session:3
