#!/bin/sh

# navigate to classroom first, so we start in that directory by default
cd ~/src/logan
session="logan"
tmux start-server

# start a new session
# run npm start
tmux new-session -d -s $session -n server
tmux send-keys "npm start" C-m

# make new window, split horizontally. Run make dev in first pane (second pane is for tsc)
tmux new-window -t $session:2 -n build
tmux send-keys "make dev" C-m
tmux splitw -h -p 50

# make new window (for nvim)
tmux new-window -t $session:3
