#!/bin/bash

tmux start-server

# Kept as usage example
# cd ~/src/logan
# tmux new-session -d -s logan
# # 0 is for vim
# tmux send-keys "vi" C-m
# # 1 is for terminal
# tmux new-window -t logan:1
# # 7 runs the server
# tmux new-window -t logan:7 -n server
# tmux send-keys "npm start" C-m
# # 8 is build
# tmux new-window -t logan:8 -n build
# tmux send-keys "make dev" C-m
# # 9 is for tsc
# tmux new-window -t logan:9 -n tsc

cd ~/src/dotfiles
tmux new-session -d -s dotfiles
# 0 is for vim
tmux send-keys "vi" C-m
# 1 is for terminal
tmux new-window -t dotfiles:1
