#!/bin/bash
# from https://waylonwalker.com/tmux-nav-2021/

not_in_tmux() {
   [ -z "$TMUX" ]
 }

DIR=$1

# If no arguments are passed in try to immediately attach or start without further input
echo "$DIR"
if [ -z "$DIR" ]; then
   if not_in_tmux; then
     tmux attach && exit 1 || DIR="--start"
   else
       exit 1
   fi
fi

session_name=$(basename "$DIR" | tr '.' '_')
path_name=$DIR

echo session name is \""$session_name"\"
echo path name is "$path_name"

if [ -z "$session_name" ]; then
    # operation cancelled by user
    exit 1
fi

maybe_init_classroom_session() {
  if [[ "$path_name" == *"classroom"* ]]; then
    # 0 is for vim
    tmux send-keys -t "$session_name:0" "vi" C-m

    # 1 is for terminal
    tmux new-window -t "$session_name:1" -c "$path_name"

    # 2 is for cdk
    # tmux new-window -t "$session_name:2" -n cdk -c "$path_name"
    # tmux send-keys -t "$session_name:2" "cd cdk" C-m
    # tmux send-keys -t "$session_name:2" "npm install" C-m

    # 6 for test
    tmux new-window -t "$session_name:6" -n test -c "$path_name"
    # production-quick needed for the analysis bundle, static commit file
    # tmux send-keys -t "$session_name:6" "yarn; make production-quick" C-m

    # 7 is for server
    tmux new-window -t "$session_name:7" -n server -c "$path_name"
    # tmux send-keys -t "$session_name:7" "yarn; make download-environment; nodemon app.js | ./node_modules/.bin/bunyan" C-m

    # 8 is for build
    tmux new-window -t "$session_name:8" -n build -c "$path_name"
    # tmux send-keys -t "$session_name:8" "make download-environment; make dev" C-m

    # 9 is for tsc
    tmux new-window -t "$session_name:9" -n tsc -c "$path_name"
  fi
}

create_if_needed_and_attach() {
  # enable core dumps for this session
  ulimit -c unlimited

  if not_in_tmux; then
    tmux new-session -As "$session_name" -c "$path_name"
    maybe_init_classroom_session
  else
    if ! tmux has-session -t "=$session_name" 2>/dev/null; then
      TMUX="" tmux new-session -Ad -s "$session_name" -c "$path_name"
      maybe_init_classroom_session
    fi
    tmux switch-client -t "$session_name"
  fi
}

attatch_to_first_session() {
  tmux attach -t "$(tmux list-sessions -F "${session_name}" | head -n 1)"
  tmux choose-tree -Za
}

create_if_needed_and_attach || attatch_to_first_session
